### ISSUE TITLE
Name Option 2

### ISSUE THREAD

**Issue by MParlikar** [CasperLabs/Governance#4]
Chain Name: Casper
Token Name: Casper
Token Symbol: CSPR
Name for gas: plasm

Please vote using a reaction

**Comment by MParlikar** [comment]
Please vote using a reaction.

**Comment by mikeyun** [comment]
I support this option, and I think we should protect these names to make sure we can use them.

**Comment by MParlikar** [comment]
Other meanings of Casper: "Casper (with the same sounding Kasper) is a family and personal name derived from Chaldean that means "Treasurer". The origins of the name have been traced as far back as the Old Testament and variations of the name have been adopted by a variety of cultures and languages." https://en.wikipedia.org/wiki/Casper

**Comment by adamhackbarth** [comment]
I favor this option because you definitely want to distance yourself from the "ghost" image. Sure Casper was a cute idea at the start, but if Casper one day becomes as recognizable as Ethereum or Bitcoin, you will have a very difficult time trying to sell merch when the right holders of the cartoon character catch wind of it.

**Comment by adamhackbarth** [comment]
Two suggestions for "gas"

A) Name for gas: Zam (a shortened version for plasm and/or as a nod to Zamfir)
B) Name for gas: Gas (keeping the established standard used in Ethereum so users feel a connection to Ethereum and an instant understanding is established.

**Comment by MParlikar** [comment]
we are in talks with the owners of the cartoon - as a mascot for us.

**Comment by adamhackbarth** [comment]
That's great if it can be negotiated at a low price. I'd hate for it to be a codec moment for the Casper Labs team.

Codec moment... Kodak moment... believe it or not, that was unintentional.

**Comment by MParlikar** [comment]
Don't worry, the price isn't insane.  We won't do that.

**Comment by colga63768** [comment]
Mascots rule 🤗 brandability, friendly, decentralized, transparent and just plain fun 😉❤️

**Comment by Blank101** [comment]
This is the best choice so far out of the choices available. That being said, I'm not entirely sold on naming the chain after the consensus mechanism. What if a new consensus mechanism is used in the future? Also, Ethereum Serenity will be using Casper PoS, so there is that too.

A name should capture the essence of the whole product IMO.

**Comment by sacherjj** [comment]
For the branch choice, we need to count the gas.  So Efficient Counting Toward Origin -> ECTO plasm.

**Comment by kirkwood** [comment]
I like "Casper" for the name of the chain and the company and so on. It has good recognition and already some buzz around it.

However, I'm having trouble saying something like "five and a half caspers." "Alice sends a casper to Bob." "You owe me three casper." "Casperi?" "Caspera?" I'm not even sure how to pluralize it, and this is probably because a name is hard and weird to pluralize.

**Comment by Ojimadu** [comment]
Thanks everyone for the suggestions. A name has been chosen by the team so we can close this out. Please refer to issue #5
